spring:
  application:
    name: zuul-server
  servlet:
    multipart:
      max-file-size: 10MB #配置上传文件的单个文件最大尺寸
      max-request-size: 10MB #配置上传多个文件最大容量
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    instance-id: :${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:7999/eureka/ # Eureka服务端的注册中心