spring:
  application:
    name: zuul-server
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    instance-id: :${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:7999/eureka/ # Eureka服务端的注册中心
zuul:
  routes: # 配置Zuul的路由和相关属性
    server_provide:
      path: /service/**
      serviceId: SERVER-PROVIDE
    config_server:
      path: /config/**
      serviceId: CONFIG-SERVER